### ISSUE TITLE
Plugin didn't work

### ISSUE THREAD

**Issue by avescarelo** [Zerthick/NoSleep#1]
I instaled the plugin. 
When i tryed a sleep, time is chaning /:

## Versions:
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-4f54ce0d
    Sponge: 1.12.2-7.1.5-SNAPSHOT
    SpongeForge: 1.12.2-2768-7.1.5-RC3506
    Minecraft Forge: 14.23.5.2772

## Mods:
Antique Atlas, AppleCore, AutoRegLib, Carry On, Cases, ContainerFix, CraftTweaker JEI Support, CraftTweaker2, Earthworks, Example Mod, Fast Leaf Decay, JurassiCraft, Just Enough Items, LLibrary, Ore Veins, Quark, Rough Mobs 2, Rustic, Spice of Life: Carrot Edition, SpongeForge, The Betweenlands, Wearable Backpacks

## Plugins:
ActionBroadcaster, GriefPrevention, LangSwitch, LuckPerms, NoSleep, Nucleus, ShabbyHolograms, SmoofyDungeon, Soulbound, Total Economy, UCFA, UltimateChat, VoxelSniper

## Links:
latest server log: https://gist.github.com/pingvikin/97a5f9e10ec2f7ad62667978934647e1

**Comment by Zerthick** [comment]
Hello! Sorry for the long wait! Can you see if this version works for you? https://github.com/Zerthick/NoSleep/releases/tag/v1.2.1
